import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ConfirmAlertContextProvider from "./components/providers/ConfirmAlertContextProvider";
import SessionProvider from "./components/SessionProvider";
import "./main.scss";

const instrumentSans = Instrument_Sans({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={instrumentSans.className}>
        <SessionProvider>
          <Toaster />
          <ConfirmAlertContextProvider>{children}</ConfirmAlertContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
